# IAM User access configuration
# AWS_ACCESS_KEY="AKIA3WAPWHKUASIIHWZF"
# AWS_SECRET_ACCESS_KEY="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"
AWS_REGION="us-east-1"

AWS_ACCESS_KEY="AKIA3WAPWHKUASIIHWZF"
AWS_SECRET_ACCESS_KEY="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"



